In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [4]:
"""
creating an array
"""
print(np.arange(3))
print(np.arange(3,9))
print(np.arange(3,9,2))

[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [8]:
#seed for reproducibility
np.random.seed(0)

arr1=np.random.randint(10,size=6)
arr2=np.random.randint(10,size=(3,4))
arr3=np.random.randint(10,size=(3,4,5))
print(arr1)
print(arr2)
print(arr3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [16]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)
print(arr2.itemsize)
print(arr2.nbytes)

2
(3, 4)
12
int32
4
48


In [18]:
"""
array slicing
"""
arr=np.arange(10)
print(arr)

print(arr[3:7])
print(arr[:5])
print(arr[5:])
print(arr[::3])
print(arr[2:8:2])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[2 4 6]


In [23]:
"""
multi-dimensional
"""
arr=np.random.randint(10,size=(6,8))
print(arr)

print(arr [3:5,4:7])
#실습문제
print(arr[:2,:3])
print(arr[:3,::2])

[[3 0 0 6 0 6 3 3]
 [8 8 8 2 3 2 0 8]
 [8 3 8 2 8 4 3 0]
 [4 3 6 9 8 0 8 5]
 [9 0 9 6 5 3 1 8]
 [0 4 9 6 5 7 8 8]]
[[8 0 8]
 [5 3 1]]
[[3 0 0]
 [8 8 8]]
[[3 0 0 3]
 [8 8 3 0]
 [8 8 8 3]]


In [25]:
"""
subarrays as views
"""
np.random.seed(1)
arr=np.random.randint(10,size=(3,4))
print(arr,"\n")

arr_sub=arr[:2,:2]
print(arr_sub,"\n")

arr_sub[0,0]=99
print(arr)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]] 

[[5 8]
 [0 0]] 

[[99  8  9  5]
 [ 0  0  1  7]
 [ 6  9  2  4]]


In [26]:
#copy
arr=np.random.randint(10,size=(2,3))
print(arr)
arr_sub=arr[:2,:2].copy()
print(arr_sub,"\n")

arr_sub[0,0]=99
print(arr_sub)

[[5 2 4]
 [2 4 7]]
[[5 2]
 [2 4]] 

[[99  2]
 [ 2  4]]


In [33]:
"""
reshaping of arrays
"""
arr=np.random.randint(10,size=(1,9))
print(arr)
grid=arr.reshape(3,3)
print(grid)

[[8 7 3 6 5 1 9 3 4]]
[[8 7 3]
 [6 5 1]
 [9 3 4]]


In [37]:
#np.newaxis

arr=np.array([1,2,3])
print(arr)
print("arr.ndim=",arr.ndim)
print("arr.shape=",arr.shape)

#arr_new=arr[:,np.newaxis]
arr_new=arr[np.newaxis,:]
print(arr_new)
print("arr_new.ndim=",arr_new.ndim)
print("arr_new.shape=",arr_new.shape)

[1 2 3]
arr.ndim= 1
arr.shape= (3,)
[[1 2 3]]
arr_new.ndim= 2
arr_new.shape= (1, 3)


In [40]:
#concatenate
arr_1=np.array([1,2,3])
arr_2=np.array([4,5,6])
arr_3=np.array([7,8,9])

arr_total=np.concatenate([arr_1,arr_2,arr_3])
arr_total1=np.vstack([arr_1,arr_2,arr_3])
print(arr_total,"\n")
print(arr_total1,"\n")

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [46]:
arr=[1,2,3,99,99,3,2,1]
print(arr,"\n")

arr_1,arr_2,arr_3=np.split(arr,[3,5])
print(arr_1)
print(arr_2)
print(arr_3)

[1, 2, 3, 99, 99, 3, 2, 1] 

[1 2 3]
[99 99]
[3 2 1]
