In [1]:
import numpy as np

In [2]:
def compute_reciprocals(values):
    output=np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]
    return output

values=np.random.randint(1,10,size=5)
print(values)

[4 2 4 5 5]


In [3]:
big_array=np.random.randint(1,100,size=1000000)
#해당코드를 여러번 실행시켜줌
%timeit compute_reciprocals(big_array)

4.65 s ± 649 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%timeit 1/big_array

6.51 ms ± 343 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
np.random.seed(1)
arr1=np.random.randint(10,size=5)
arr2=np.random.randint(10,size=5)
print(arr1,arr2)

arr1=arr1-2
print(arr1,arr2)

arr3=arr1+arr2
print(arr3)

arr4=np.random.randint(10,size=(3,5))
print(arr4)

arr5=arr4**2
print(arr5)

[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2] [0 1 7 6 9]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [11]:
x=np.array([-2,-1,0,1,2])
np.abs(x)

array([2, 1, 0, 1, 2])

In [12]:
x=np.array([3-4j,4-3j,2+0j,0+1j])
np.abs(x)

array([5., 5., 2., 1.])

In [18]:
theta=np.linspace(1,np.pi,3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

x=np.linspace(0,100,11)
print(x)

[1.         2.07079633 3.14159265]
[8.41470985e-01 8.77582562e-01 1.22464680e-16]
[ 0.54030231 -0.47942554 -1.        ]
[ 1.55740772e+00 -1.83048772e+00 -1.22464680e-16]
[  1.   10.9  20.8  30.7  40.6  50.5  60.4  70.3  80.2  90.1 100. ]


In [20]:
x=np.arange(1,5)
aggr=np.add.reduce(x)
print(aggr)
aggr=np.multiply.reduce(x)
print(aggr)

10
24


In [27]:
x=np.arange(1,5)
print(x)
accum=np.add.accumulate(x)
print(accum)
accum=np.multiply.accumulate(x)
print(accum)

[1 2 3 4]
[ 1  3  6 10]
[ 1  2  6 24]


In [30]:
np.random.seed(1)
arr=np.random.rand(1000000)
print(arr)
np.sum(arr)

[4.17022005e-01 7.20324493e-01 1.14374817e-04 ... 4.93233752e-01
 1.08809709e-01 3.70251829e-01]


499948.2541286655

In [31]:
%timeit sum(arr)

197 ms ± 38.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [32]:
%timeit np.sum(arr)

1.99 ms ± 149 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [33]:
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.percentile(arr,90))

print(np.any(arr>1))
print(np.all(arr>0))

0.9999995556201814
3.0077687129814734e-07
0.4999482541286655
0.500166468682165
0.899807132583175
False
True


In [34]:
np.random.seed(5)
arr=np.random.randint(10,size=(3,4))
print(arr)

print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[12 14 17  8]
[15 28  8]
