In [3]:
import numpy as np

In [4]:
a=np.ones((3,3))
b=np.arange(3)
a+b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [5]:
a=np.arange(3)
a=a[:,np.newaxis]
b=np.arange(3)
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [6]:
a=np.ones((2,3))
b=np.arange(3)
a+b

array([[1., 2., 3.],
       [1., 2., 3.]])

In [13]:
x=np.array([1,2,3,4,5])
print(x)
print(x<3)
print(x>=3)
print(x!=3)
print(x==3)

[1 2 3 4 5]
[ True  True False False False]
[False False  True  True  True]
[ True  True False  True  True]
[False False  True False False]


In [25]:
np.random.seed(0)
x=np.random.randint(10,size=(3,4))
print(x)
print(x<6)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[ True  True  True  True]
 [False False  True  True]
 [ True  True False False]]


In [24]:
print(x)
print(np.count_nonzero(x<6))
print(np.sum(x<6))

print(np.any(x>8))
print(np.any(x>9))
print(np.all(x>1))

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
8
8
True
False
False


In [31]:
print(x<5)
print(np.std(x[x<5]))

[[False  True  True  True]
 [False False  True False]
 [ True  True False False]]
1.2583057392117916


In [49]:
np.random.seed(1)
x=np.random.randint(100,size=10)
print(x[2],x[4],x[6])
ind=[2,4,6]
print(x[ind])

72 75 79
[72 75 79]


In [48]:
np.random.seed(2)
x=np.random.randint(10,size=(3,5))
print(x)
row=[0,1,2]
col=[1,3,2]
x[row,col]

[[8 8 6 2 8]
 [7 2 1 5 4]
 [4 5 7 3 6]]


array([8, 5, 7])

In [47]:
np.random.seed(3)
x=np.random.randint(10,size=(3,5))
row=np.array([0,1,2])
col=np.array([2,1,4])
x[row[:,np.newaxis],col]

array([[3, 9, 8],
       [3, 5, 9],
       [6, 7, 4]])

In [53]:
x=np.arange(1,13).reshape(3,4)
print(x)
print(x[2,[2,0,1]])
print(x[1:,[2,0,1]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[11  9 10]
[[ 7  5  6]
 [11  9 10]]


In [57]:
mean=[0,0]
cov=[[1,2],
    [2,5]]

rand=np.random.RandomState(1)
x=rand.multivariate_normal(mean,cov,100)
print(x)

[[-1.26659039e+00 -3.71998007e+00]
 [ 8.98574387e-01  1.00797760e+00]
 [ 8.12283322e-02 -2.29506499e+00]
 [-1.32069461e+00 -4.01236325e+00]
 [-1.99323780e-01 -7.51126722e-01]
 [-5.62429879e-01 -3.58770608e+00]
 [ 4.44845894e-01  6.58255553e-01]
 [-6.26556217e-01 -2.70315425e+00]
 [ 4.95244764e-01  2.45439522e-01]
 [-2.62034143e-01 -1.77174030e-03]
 [ 5.78772733e-01  2.63632100e+00]
 [-1.02525747e+00 -1.93129454e+00]
 [-5.70631049e-01 -2.11768692e+00]
 [ 4.71639223e-01  1.25768272e-01]
 [ 4.45380634e-02  6.81577017e-01]
 [ 7.90842213e-01  1.47981907e+00]
 [ 9.58310989e-01  1.39872339e+00]
 [ 6.24997094e-01  1.49516840e+00]
 [ 9.42553159e-01  2.52925434e+00]
 [-1.81742527e+00 -3.58446991e+00]
 [ 5.16913839e-01  2.87177733e-01]
 [ 4.26099193e-02  1.93476910e+00]
 [ 1.96827436e-01 -2.14295655e-01]
 [-9.80115753e-01 -9.29089657e-02]
 [-3.47205801e-01 -1.70173123e-01]
 [-1.42521035e-01 -7.25348701e-01]
 [ 1.18923685e+00  2.49294590e+00]
 [-3.14978696e-02  5.58913783e-01]
 [-1.13143694e+00 -1